# Define the stages.
stages:
  # Create a static code analysis stage.
  - analyze

analyze:ec:
  # Add to the analysis stage.
  stage: analyze
  # Use the latest ec Docker image.
  image: mstruebing/editorconfig-checker:latest
  script:
    # Check that all text complies with the EditorConfig file.
    - ec

analyze:shfmt:
  # Add to the analysis stage.
  stage: analyze
  # Use the latest Alpine Linux shfmt Docker image.
  image: mvdan/shfmt:latest-alpine
  script:
    # Check that all Bash code has proper formatting.
    - shfmt -d .

shell check:
  image: koalaman/shellcheck-alpine:stable
  stage: analyze
  before_script:
    - shellcheck --version
  script:
    - shellcheck scripts/**/*.sh # path to your shell scripts
